alias repl := nrepl

# Shows available recipes
help:
  just --list

run:
  clojure -M -m example.main

nrepl:
  clojure -M:dev:repl/nrepl

conjure:
  clojure -M:dev:repl/conjure

rebel:
  clojure -M:dev:repl/rebel

nrebel *FLAGS: 
  clojure -M:dev:repl/nrebel -p {{read(".nrepl-port")}} {{FLAGS}}

check *FLAGS:
  clojure -T:cljfmt check -- {{FLAGS}}

fix *FLAGS: 
  clojure -T:cljfmt fix -- {{FLAGS}}
